config/routes.rb
Rails.application.routes.draw do
  resources :movie_rentals

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :movie_rentals
  has_many :users, through: :movie_rentals

  def rent(movie)
    movies << movie
  end
end

app/models/movie_rental.rb
class MovieRental < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :movie_rentals
  has_many :movies, through: :movie_rentals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_rentals_controller.rb
class MovieRentalsController < ApplicationController
  before_action :set_movie_rental, only: [:show, :edit, :update, :destroy]

  # GET /movie_rentals
  # GET /movie_rentals.json
  def index
    @movie_rentals = MovieRental.all
  end

  # GET /movie_rentals/1
  # GET /movie_rentals/1.json
  def show
  end

  # GET /movie_rentals/new
  def new
    @movie_rental = MovieRental.new
  end

  # GET /movie_rentals/1/edit
  def edit
  end

  # POST /movie_rentals
  # POST /movie_rentals.json
  def create
    @movie_rental = MovieRental.new(movie_rental_params)

    respond_to do |format|
      if @movie_rental.save
        format.html { redirect_to @movie_rental, notice: 'Movie rental was successfully created.' }
        format.json { render :show, status: :created, location: @movie_rental }
      else
        format.html { render :new }
        format.json { render json: @movie_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_rentals/1
  # PATCH/PUT /movie_rentals/1.json
  def update
    respond_to do |format|
      if @movie_rental.update(movie_rental_params)
        format.html { redirect_to @movie_rental, notice: 'Movie rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_rental }
      else
        format.html { render :edit }
        format.json { render json: @movie_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_rentals/1
  # DELETE /movie_rentals/1.json
  def destroy
    @movie_rental.destroy
    respond_to do |format|
      format.html { redirect_to movie_rentals_url, notice: 'Movie rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_rental
      @movie_rental = MovieRental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_rental_params
      params.require(:movie_rental).permit(:userid, :movieid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_rentals_helper.rb
module MovieRentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day18asgn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie_rentals/_form.html.erb
<%= form_for(@movie_rental) do |f| %>
  <% if @movie_rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_rental.errors.count, "error") %> prohibited this movie_rental from being saved:</h2>

      <ul>
      <% @movie_rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :movieid %><br>
    <%= f.text_field :movieid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_rentals/edit.html.erb
<h1>Editing movie_rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_rental %> |
<%= link_to 'Back', movie_rentals_path %>

app/views/movie_rentals/index.html.erb
<h1>Listing movie_rentals</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Movieid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_rentals.each do |movie_rental| %>
      <tr>
        <td><%= movie_rental.userid %></td>
        <td><%= movie_rental.movieid %></td>
        <td><%= link_to 'Show', movie_rental %></td>
        <td><%= link_to 'Edit', edit_movie_rental_path(movie_rental) %></td>
        <td><%= link_to 'Destroy', movie_rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie rental', new_movie_rental_path %>

app/views/movie_rentals/new.html.erb
<h1>New movie_rental</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_rentals_path %>

app/views/movie_rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @movie_rental.userid %>
</p>

<p>
  <strong>Movieid:</strong>
  <%= @movie_rental.movieid %>
</p>

<%= link_to 'Edit', edit_movie_rental_path(@movie_rental) %> |
<%= link_to 'Back', movie_rentals_path %>